name: cmsplugin-blog
package-name: cmsplugin-blog
url: https://github.com/fivethreeo/cmsplugin-blog
author:
  name: fivethreeo
  url: http://github.com/fivethreeo/
installed-apps:
  - cmsplugin_blog
  - djangocms_utils
  - simple_translation
  - tagging
  - missing
version: 1.1.2.dev4
description: simple blog
license:
  name: BSD
  text: !literal-include LICENSE.txt